version: 1.1
kind: operation
name: build
params:
  destination:
    connection: docker-connection
    value: polyaxon/polyaxon-examples
runPatch:
  init:
  - dockerfile:
      image: "tensorflow/tensorflow:2.2.0"
      run:
      - 'pip3 install --no-cache-dir -U polyaxon["s3","gcs","azure","polyboard","polytune"]'
      - pip3 install mxnet
      - pip3 install scikit-learn
      - pip3 install xgboost
      - pip3 install keras
      - pip3 install tensorflow_datasets
      - pip3 install torch
      - pip3 install torchvision
      - pip3 install pytorch-ignite
      - pip3 install tensorboard
      - pip3 install matplotlib
      - pip3 install fastai
      - pip3 install vega-datasets
      - pip3 install joblib
      langEnv: 'en_US.UTF-8'
hubRef: kaniko
